.PHONY: clean


clean:
		rm -rf *.log  csrc  simv*  *.key *.vpd  DVEfiles coverage *.vdb output.txt *.svf *.logv *.rpt *.tcl


clean_all: clean
		rm -rf ./netlist/* ./log/* ./reports/* ./FM_INFO ./jgproject ./output/* ./work/* ./Synopsys* ./*.txt ./rtl/*
